services:
  # FastAPI Application
  app:
    build: .
    container_name: rag-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - workoflow-rag-app:/app
    networks:
      - rag-network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  rag-network:
    driver: bridge

volumes:
  workoflow-rag-app: