services:
  # FastAPI Application with Debug Support
  app:
    build: .
    container_name: rag-api
    ports:
      - "8000:8000"
      - "5678:5678"  # Debug port
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG_MODE=true
    env_file:
      - .env
    volumes:
      - ./app:/app
      - ./example_data:/example_data:ro
    networks:
      - rag-network
    # Start with debugpy, waiting for client connection
    command: python -m debugpy --listen 0.0.0.0:5678 --wait-for-client -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload

networks:
  rag-network:
    driver: bridge